import Link from "next/link";
import FeedWithFilter from "@/components/feed-with-filter";

// Revalidate every 5 minutes to check for updated feed.json
export const revalidate = 300; // 5 minutes in seconds

interface FeedData {
  generatedAt: string;
  startDate: string;
  endDate: string;
  items: any[];
  stats: {
    totalItems: number;
    byType: Record<string, number>;
    sourceStats: Record<string, number>;
    errors: Record<string, string | null>;
  };
}

async function getFeedData(): Promise<FeedData> {
  // Always load from the JSON cache file (generated by generate-feed.ts script)
  const fs = await import("fs/promises");
  const path = await import("path");
  const cachePath = path.join(process.cwd(), "public", "data", "feed.json");

  try {
    const fileContent = await fs.readFile(cachePath, "utf-8");
    const cachedData = JSON.parse(fileContent);

    console.log(
      `Loaded feed.json (generated: ${cachedData.generatedAt}, items: ${cachedData.items.length})`
    );

    return cachedData;
  } catch (error) {
    console.error("Error reading feed.json:", error);
    // Return empty fallback data structure if file doesn't exist
    return {
      generatedAt: new Date().toISOString().split("T")[0],
      startDate: new Date(Date.now() - 365 * 24 * 60 * 60 * 1000)
        .toISOString()
        .split("T")[0],
      endDate: new Date().toISOString().split("T")[0],
      items: [],
      stats: {
        totalItems: 0,
        byType: {},
        sourceStats: {},
        errors: {
          general:
            error instanceof Error
              ? error.message
              : "Feed file not found. Run 'npm run generate-feed' to generate it.",
        },
      },
    };
  }
}

export default async function FeedPage() {
  const feedData = await getFeedData();

  console.log(`Feed data last generated at: ${feedData.generatedAt}`);
  console.log(`Total items: ${feedData.items.length}`);

  // Log any errors for debugging
  const errors = Object.entries(feedData.stats.errors).filter(
    ([_, error]) => error
  );
  if (errors.length > 0) {
    console.warn("Feed data source errors:", errors);
  }

  return (
    <main className="min-h-screen w-full flex flex-col bg-primary-gray text-primary-black font-inter overflow-x-hidden">
      <div className="flex-1 flex flex-col w-full px-4 py-4 sm:p-6 lg:py-8 lg:px-8 gap-4 sm:gap-6">
        {/* Card 1: Header only */}
        <header className="shrink-0 rounded-2xl overflow-hidden bg-primary-white flex flex-col px-6 py-6">
          <h1 className="text-2xl sm:text-3xl mb-2">
            <Link href="/" className="font-bold text-gray-800 hover:opacity-70 transition-opacity">
              gndclouds
            </Link>
            <span className="font-bold text-gray-800"> / feed</span>
          </h1>
          <div className="flex flex-wrap items-center gap-x-4 gap-y-1 text-sm text-gray-500">
            <span>Last updated: {feedData.generatedAt}</span>
            {Object.keys(feedData.stats.sourceStats).length > 0 && (
              <span>
                Sources:{" "}
                {Object.entries(feedData.stats.sourceStats)
                  .map(([source, count]) => `${source}: ${count}`)
                  .join(", ")}
              </span>
            )}
          </div>
        </header>

        {/* Card 2: Filters — Card 3: Feed items (inside FeedWithFilter when cardLayout) */}
        <FeedWithFilter data={feedData.items} cardLayout />

        {/* Footer — matches landing footer card */}
        <footer className="shrink-0 rounded-2xl overflow-hidden bg-primary-white dark:bg-backgroundDark flex flex-wrap justify-between items-center gap-x-4 gap-y-1 px-6 py-4 text-sm text-primary-black dark:text-textDark">
          <nav className="flex flex-wrap items-center justify-start gap-x-4 gap-y-1">
            <span className="text-gray-400">feed</span>
            <Link
              href="https://webring.xxiivv.com/#xxiivv"
              target="_blank"
              rel="noopener noreferrer"
              className="transition-opacity hover:opacity-70"
              data-umami-event="outbound-webring"
            >
              webring <span className="font-mono">↗</span>
            </Link>
            <Link
              href="/cv"
              className="transition-opacity hover:opacity-70"
              data-umami-event="nav-cv"
            >
              cv
            </Link>
            <Link
              href="https://are.na/gndclouds"
              target="_blank"
              rel="noopener noreferrer"
              className="transition-opacity hover:opacity-70"
              data-umami-event="outbound-arena"
            >
              are.na <span className="font-mono">↗</span>
            </Link>
            <Link
              href="https://bsky.app/profile/gndclouds.earth"
              target="_blank"
              rel="noopener noreferrer"
              className="transition-opacity hover:opacity-70"
              data-umami-event="outbound-bluesky"
            >
              bluesky <span className="font-mono">↗</span>
            </Link>
            <Link
              href="https://github.com/gndclouds"
              target="_blank"
              rel="noopener noreferrer"
              className="transition-opacity hover:opacity-70"
              data-umami-event="outbound-github"
            >
              github <span className="font-mono">↗</span>
            </Link>
            <Link
              href="/newsletters"
              className="transition-opacity hover:opacity-70"
              data-umami-event="nav-newsletter"
            >
              newsletter
            </Link>
          </nav>
        </footer>
      </div>
    </main>
  );
}
