import CollectionHero from "@/components/collection-hero";
import FeedWithFilter from "@/components/feed-with-filter";

// Revalidate every 5 minutes to check for updated feed.json
export const revalidate = 300; // 5 minutes in seconds

interface FeedData {
  generatedAt: string;
  startDate: string;
  endDate: string;
  items: any[];
  stats: {
    totalItems: number;
    byType: Record<string, number>;
    sourceStats: Record<string, number>;
    errors: Record<string, string | null>;
  };
}

async function getFeedData(): Promise<FeedData> {
  // Always load from the JSON cache file (generated by generate-feed.ts script)
  const fs = await import("fs/promises");
  const path = await import("path");
  const cachePath = path.join(process.cwd(), "public", "data", "feed.json");

  try {
    const fileContent = await fs.readFile(cachePath, "utf-8");
    const cachedData = JSON.parse(fileContent);

    console.log(
      `Loaded feed.json (generated: ${cachedData.generatedAt}, items: ${cachedData.items.length})`
    );

    return cachedData;
  } catch (error) {
    console.error("Error reading feed.json:", error);
    // Return empty fallback data structure if file doesn't exist
    return {
      generatedAt: new Date().toISOString().split("T")[0],
      startDate: new Date(Date.now() - 365 * 24 * 60 * 60 * 1000)
        .toISOString()
        .split("T")[0],
      endDate: new Date().toISOString().split("T")[0],
      items: [],
      stats: {
        totalItems: 0,
        byType: {},
        sourceStats: {},
        errors: {
          general:
            error instanceof Error
              ? error.message
              : "Feed file not found. Run 'npm run generate-feed' to generate it.",
        },
      },
    };
  }
}

export default async function FeedPage() {
  const feedData = await getFeedData();

  console.log(`Feed data last generated at: ${feedData.generatedAt}`);
  console.log(`Total items: ${feedData.items.length}`);

  // Log any errors for debugging
  const errors = Object.entries(feedData.stats.errors).filter(
    ([_, error]) => error
  );
  if (errors.length > 0) {
    console.warn("Feed data source errors:", errors);
  }

  return (
    <div className="flex flex-col">
      <CollectionHero
        name="Feed"
        projects={feedData.items}
        allProjects={feedData.items}
      />
      <main className="">
        <div className="mb-8">
          <div className="flex justify-between items-center mb-4 px-4">
            <h2 className="text-2xl font-bold">Latest Updates</h2>
            <div className="text-sm text-gray-600">
              Last updated: {feedData.generatedAt}
            </div>
          </div>

          {/* Show source statistics */}
          <div className="mb-4 text-sm text-gray-600 px-4">
            <span>Sources: </span>
            {Object.entries(feedData.stats.sourceStats).map(
              ([source, count], index) => (
                <span key={source}>
                  {source}: {count}
                  {index < Object.entries(feedData.stats.sourceStats).length - 1
                    ? ", "
                    : ""}
                </span>
              )
            )}
          </div>

          <FeedWithFilter data={feedData.items} />
        </div>
      </main>
    </div>
  );
}
